app:
  port: 8080

database:
  host: localhost
  port: 5433
  user: postgres
  password: adaremit
  name: user

redis:
  host: 127.0.0.1
  port: 6379
  password:

secret:
  jwt_secret: "Khz0yd8Tf8yAG80PuQAX2nHEjGHiEgh/gQO2PNhMZjY="
